// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQOblX0Ypbe3rh0KfuVnWREgQbj--fvAI',
    appId: '1:279190733000:web:4f0ee1c0e40c18464365fd',
    messagingSenderId: '279190733000',
    projectId: 'finle-project-app',
    authDomain: 'finle-project-app.firebaseapp.com',
    storageBucket: 'finle-project-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9LAeX6ecGU3kQ5yARwDsuVFEDqeqsWhE',
    appId: '1:279190733000:android:9f3a7ab9911545d94365fd',
    messagingSenderId: '279190733000',
    projectId: 'finle-project-app',
    storageBucket: 'finle-project-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZyQ1G_IL5DKFw9rPbPztCc-9SHG8HF8',
    appId: '1:279190733000:ios:ece96e75ac9d57894365fd',
    messagingSenderId: '279190733000',
    projectId: 'finle-project-app',
    storageBucket: 'finle-project-app.appspot.com',
    iosClientId: '279190733000-4tn17b4p83tcc88hc0v3d0m9jqekm5vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.finleprojectflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZyQ1G_IL5DKFw9rPbPztCc-9SHG8HF8',
    appId: '1:279190733000:ios:ece96e75ac9d57894365fd',
    messagingSenderId: '279190733000',
    projectId: 'finle-project-app',
    storageBucket: 'finle-project-app.appspot.com',
    iosClientId: '279190733000-4tn17b4p83tcc88hc0v3d0m9jqekm5vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.finleprojectflutter',
  );
}
